name: Generate Snake

on:
  schedule:
    # Run at 12 AM UTC every day
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: Yash04577
          outputs: dist/snake.svg

      - name: Upload snake.svg
        uses: actions/upload-artifact@v2
        with:
          name: snake.svg
          path: dist/snake.svg

      - name: Commit and push if needed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add dist/snake.svg
          git commit -m "Generate snake animation" || echo "No changes to commit"
          git push
